// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFinanciero.Infrastructure.Persistence;

#nullable disable

namespace SistemaFinanciero.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinancialDbContext))]
    [Migration("20260926182509_AddInvoicePaymentTerm")]
    partial class AddInvoicePaymentTerm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RolesClaims", "seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UsuariosClaims", "seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UsuariosLogins", "seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_UsuariosRoles_UserId");

                    b.ToTable("UsuariosRoles", "seguridad");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UsuariosTokens", "seguridad");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Catalogs.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DefaultIncomeCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("ReferencePriceCrc")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ReferencePriceUsd")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_ProductosServicios_Code");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DefaultIncomeCategoryId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_ProductosServicios_IsActive_Name");

                    b.ToTable("ProductosServicios", "catalogos", t =>
                        {
                            t.HasCheckConstraint("CK_ProductosServicios_Codigo_NoVacio", "LEN(LTRIM(RTRIM([Code]))) > 0");

                            t.HasCheckConstraint("CK_ProductosServicios_PriceCrc", "[ReferencePriceCrc] IS NULL OR [ReferencePriceCrc] > 0");

                            t.HasCheckConstraint("CK_ProductosServicios_PriceUsd", "[ReferencePriceUsd] IS NULL OR [ReferencePriceUsd] > 0");

                            t.HasCheckConstraint("CK_ProductosServicios_Type", "[Type] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Catalogs.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Clientes_Code");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Identification")
                        .IsUnique()
                        .HasDatabaseName("UX_Clientes_Identification")
                        .HasFilter("[Identification] IS NOT NULL");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_Clientes_IsActive_Name");

                    b.ToTable("Clientes", "catalogos", t =>
                        {
                            t.HasCheckConstraint("CK_Clientes_Codigo_NoVacio", "LEN(LTRIM(RTRIM([Code]))) > 0");
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Catalogs.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(3)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_CuentasFinancieras_Code");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("IsActive", "Currency", "Name")
                        .HasDatabaseName("IX_CuentasFinancieras_IsActive_Currency_Name");

                    b.ToTable("CuentasFinancieras", "finanzas", t =>
                        {
                            t.HasCheckConstraint("CK_CuentasFinancieras_Codigo_NoVacio", "LEN(LTRIM(RTRIM([Code]))) > 0");

                            t.HasCheckConstraint("CK_CuentasFinancieras_Currency", "[Currency] IN ('CRC', 'USD')");

                            t.HasCheckConstraint("CK_CuentasFinancieras_Type", "[Type] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Catalogs.FinancialCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_CategoriasFinancieras_Code");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("IsActive", "Kind", "Name")
                        .HasDatabaseName("IX_CategoriasFinancieras_IsActive_Kind_Name");

                    b.ToTable("CategoriasFinancieras", "catalogos", t =>
                        {
                            t.HasCheckConstraint("CK_CategoriasFinancieras_Codigo_NoVacio", "LEN(LTRIM(RTRIM([Code]))) > 0");

                            t.HasCheckConstraint("CK_CategoriasFinancieras_Kind", "[Kind] IN (1, 2)");

                            t.HasCheckConstraint("CK_CategoriasFinancieras_Parent", "[ParentId] IS NULL OR [ParentId] <> [Id]");
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Catalogs.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Identification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Proveedores_Code");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Identification")
                        .IsUnique()
                        .HasDatabaseName("UX_Proveedores_Identification")
                        .HasFilter("[Identification] IS NOT NULL");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_Proveedores_IsActive_Name");

                    b.ToTable("Proveedores", "catalogos", t =>
                        {
                            t.HasCheckConstraint("CK_Proveedores_Codigo_NoVacio", "LEN(LTRIM(RTRIM([Code]))) > 0");
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Currencies.DailyExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("CrcPerUsd");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EffectiveDate")
                        .IsUnique()
                        .HasDatabaseName("UX_TiposCambioDiarios_EffectiveDate");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("TiposCambioDiarios", "finanzas", t =>
                        {
                            t.HasCheckConstraint("CK_TiposCambioDiarios_CrcPerUsd", "[CrcPerUsd] > 0");
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ConfirmedCrcPerUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Number"));

                    b.Property<int>("PaymentTerm")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("ConfirmedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("UX_Facturas_Number");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("IX_Facturas_CustomerId_Status");

                    b.HasIndex("Status", "IssueDate")
                        .HasDatabaseName("IX_Facturas_Status_IssueDate");

                    b.ToTable("Facturas", "finanzas", t =>
                        {
                            t.HasCheckConstraint("CK_Facturas_Currency", "[Currency] IN (1, 2)");

                            t.HasCheckConstraint("CK_Facturas_DueDate", "([PaymentTerm] = 1 AND [DueDate] IS NULL) OR ([PaymentTerm] = 2 AND [DueDate] IS NOT NULL AND [DueDate] >= [IssueDate])");

                            t.HasCheckConstraint("CK_Facturas_PaymentTerm", "[PaymentTerm] IN (1, 2)");

                            t.HasCheckConstraint("CK_Facturas_Status", "[Status] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Facturas_Totals", "[GrossAmount] >= 0 AND [DiscountAmount] >= 0 AND [NetAmount] >= 0 AND [TaxAmount] >= 0 AND [TotalAmount] >= 0");

                            t.HasCheckConstraint("CK_Facturas_UsdRate", "[Currency] <> 2 OR [Status] = 1 OR [ConfirmedCrcPerUsd] > 0");
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Invoices.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CatalogItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CatalogItemId");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("IX_FacturaLineas_InvoiceId");

                    b.ToTable("FacturaLineas", "finanzas", t =>
                        {
                            t.HasCheckConstraint("CK_FacturaLineas_Amounts", "[Quantity] > 0 AND [UnitPrice] >= 0 AND [GrossAmount] >= 0 AND [DiscountAmount] >= 0 AND [DiscountAmount] <= [GrossAmount] AND [NetAmount] >= 0 AND [TaxAmount] >= 0 AND [TotalAmount] >= 0");
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Invoices.InvoiceLineTax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CalculationType")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("InvoiceLineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceLineId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_FacturaLineaImpuestos_Line_Code");

                    b.ToTable("FacturaLineaImpuestos", "finanzas", t =>
                        {
                            t.HasCheckConstraint("CK_FacturaLineaImpuestos_RateAmount", "[Rate] >= 0 AND [Amount] >= 0");

                            t.HasCheckConstraint("CK_FacturaLineaImpuestos_Type", "[CalculationType] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("IsActive", "FullName")
                        .HasDatabaseName("IX_Usuarios_IsActive_FullName");

                    b.ToTable("Usuarios", "seguridad", t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Email_UserName", "[NormalizedEmail] = [NormalizedUserName]");

                            t.HasCheckConstraint("CK_Usuarios_FullName_NoVacio", "LEN(LTRIM(RTRIM([FullName]))) > 0");
                        });
                });

            modelBuilder.Entity("SistemaFinanciero.Infrastructure.Identity.SecurityAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_EventosSeguridad_OccurredAtUtc");

                    b.HasIndex("ActorUserId", "OccurredAtUtc")
                        .HasDatabaseName("IX_EventosSeguridad_ActorUserId_OccurredAtUtc");

                    b.HasIndex("TargetUserId", "OccurredAtUtc")
                        .HasDatabaseName("IX_EventosSeguridad_TargetUserId_OccurredAtUtc");

                    b.ToTable("EventosSeguridad", "seguridad", t =>
                        {
                            t.HasCheckConstraint("CK_EventosSeguridad_Action", "[Action] BETWEEN 1 AND 9");

                            t.HasCheckConstraint("CK_EventosSeguridad_Role", "[Role] IS NULL OR [Role] IN (N'Administrador', N'Gerencia', N'Finanzas', N'Asistente')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Catalogs.CatalogItem", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ProductosServicios_Usuarios_CreatedBy");

                    b.HasOne("SistemaFinanciero.Domain.Catalogs.FinancialCategory", null)
                        .WithMany()
                        .HasForeignKey("DefaultIncomeCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ProductosServicios_CategoriasFinancieras");

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ProductosServicios_Usuarios_UpdatedBy");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Catalogs.Customer", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Clientes_Usuarios_CreatedBy");

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Clientes_Usuarios_UpdatedBy");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Catalogs.FinancialAccount", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CuentasFinancieras_Usuarios_CreatedBy");

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CuentasFinancieras_Usuarios_UpdatedBy");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Catalogs.FinancialCategory", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriasFinancieras_Usuarios_CreatedBy");

                    b.HasOne("SistemaFinanciero.Domain.Catalogs.FinancialCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_CategoriasFinancieras_Parent");

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CategoriasFinancieras_Usuarios_UpdatedBy");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Catalogs.Supplier", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Proveedores_Usuarios_CreatedBy");

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Proveedores_Usuarios_UpdatedBy");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Currencies.DailyExchangeRate", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TiposCambioDiarios_Usuarios_CreatedBy");

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TiposCambioDiarios_Usuarios_UpdatedBy");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Invoices.Invoice", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Facturas_Usuarios_CancelledBy");

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Facturas_Usuarios_ConfirmedBy");

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Usuarios_CreatedBy");

                    b.HasOne("SistemaFinanciero.Domain.Catalogs.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Clientes");

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Usuarios_UpdatedBy");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Invoices.InvoiceLine", b =>
                {
                    b.HasOne("SistemaFinanciero.Domain.Catalogs.CatalogItem", null)
                        .WithMany()
                        .HasForeignKey("CatalogItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_FacturaLineas_ProductosServicios");

                    b.HasOne("SistemaFinanciero.Domain.Invoices.Invoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FacturaLineas_Facturas");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Invoices.InvoiceLineTax", b =>
                {
                    b.HasOne("SistemaFinanciero.Domain.Invoices.InvoiceLine", null)
                        .WithMany("Taxes")
                        .HasForeignKey("InvoiceLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_FacturaLineaImpuestos_FacturaLineas");
                });

            modelBuilder.Entity("SistemaFinanciero.Infrastructure.Identity.SecurityAuditEvent", b =>
                {
                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_EventosSeguridad_Usuarios_Actor");

                    b.HasOne("SistemaFinanciero.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EventosSeguridad_Usuarios_Target");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Invoices.Invoice", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("SistemaFinanciero.Domain.Invoices.InvoiceLine", b =>
                {
                    b.Navigation("Taxes");
                });
#pragma warning restore 612, 618
        }
    }
}
